In [1]:
!pip install numpy

# Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4],[3,4,5,6]])
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [4]:
print(arr.ndim)

2


In [6]:
arr1 = np.array([2,6,9,8])
arr1

array([2, 6, 9, 8])

In [8]:
print(arr1.ndim)

1


In [9]:
print(arr.shape)

(2, 4)


In [10]:
print(arr1.shape)

(4,)


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
print(arr.data)

In [13]:
print(arr1.data)

# To generate random number using numpy

In [22]:
from numpy import random
x = random.randint(1000)
x

972

In [23]:
x1 = random.randint(100, size=(50))
x1

array([62,  6, 20, 10, 23,  7, 10, 80, 55, 49, 89, 16, 46, 13, 99, 27,  6,
       56, 33, 35, 45, 15, 20, 80, 82, 12, 89, 48, 45, 90, 75, 93, 64, 88,
       22, 39, 93,  6, 76, 71, 60, 62, 19, 83, 88, 52, 38, 63, 99, 24])

In [24]:
x2 = random.rand()
x2

0.4568219171030513

In [25]:
x3 = random.randint(100, size=(3, 5))
x3

array([[82, 56, 31, 34, 54],
       [13, 22, 35, 49, 32],
       [55, 84, 22, 58, 57]])

In [28]:
print(x3.shape)

(3, 5)


In [29]:
type(x3)

numpy.ndarray

# Matrix in numpy

In [30]:
a = np.matrix('1,2; 3,4')
a

matrix([[1, 2],
        [3, 4]])

In [31]:
type(a)

numpy.matrix

In [32]:
b = np.matrix([[5, 6, 7], [4, 6]])
b

C:\Users\DHRUVIL CHOVATIYA\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


matrix([[list([5, 6, 7]), list([4, 6])]], dtype=object)

In [33]:
type(b)

numpy.matrix

# Measure of Central Tendency Using numpy

In [34]:
import numpy as np

arr = np.array([[1,0,78], [98,60,75],[79,25,48]])
print(arr)

#min function
print(np.amin(arr))
#max function
print(np.amax(arr))

[[ 1  0 78]
 [98 60 75]
 [79 25 48]]
0
98


In [35]:
arr1 = np.array([5,8,26,45,39,26,11,30,37,70,44])
arr1

array([ 5,  8, 26, 45, 39, 26, 11, 30, 37, 70, 44])

In [36]:
np.mean(arr1)

31.0

In [37]:
np.median(arr1)

30.0

In [38]:
np.std(arr1)

18.1959036349094

In [39]:
np.var(arr1)

331.09090909090907